apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen-020301
  janus-idp.io/tekton: codegen-020301
  backstage.io/kubernetes-id: codegen-020301
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codegen-020301
resources:
- application-dev.yaml
- gitops-repository.yaml
- source-repository.yaml
- initialize-namespace.yaml
